services:

  _defaults:
    public: false
    autowire: true

  OxidEsales\Eshop\Core\Registry:
    class: OxidEsales\Eshop\Core\Registry

  OxidEsales\Eshop\Core\Config:
    factory: [ '@OxidEsales\Eshop\Core\Registry', 'getConfig' ]

  OxidEsales\Eshop\Core\Session:
    factory: [ '@OxidEsales\Eshop\Core\Registry', 'getSession' ]

  OxidEsales\Eshop\Core\Language:
    factory: [ '@OxidEsales\Eshop\Core\Registry', 'getLang' ]

  OxidEsales\Eshop\Core\UtilsDate:
    factory: [ '@OxidEsales\Eshop\Core\Registry', 'getUtilsDate' ]

  OxidEsales\Eshop\Core\Request:
    factory: [ '@OxidEsales\Eshop\Core\Registry', 'getRequest' ]

  OxidSolutionCatalysts\PayPal\Service\:
    resource: 'src/Service/*'
    public: true